services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betaloan
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" # this allows external client to interract
                    # should be removed for production

volumes:
  pgdata:
