from pydantic import BaseModel
from datetime import datetime
from typing import List

class IneligibilityReason(BaseModel):
    reason_code: str
    reason_message: str

# Define the input model for the API
class CustomerData(BaseModel):
    statement_data: dict
    user_agent_str: str
    date_of_birth: str
    location: str
    on_time_repayment: int
    late_repayment: int
    due_date_repayment: int
    credit_score: float | None
    tier: int

# Define the output schema, for logging
class LogResponse(BaseModel):

    # Autogenerated
    id: int
    timestamp: datetime

    #input fields
    credit_score : float | None
    date_of_birth:str
    location:str
    tier:int
    user_agent_str:str
    on_time_repayment:int
    late_repayment:int
    due_date_repayment:int

    # Output fields
    status:str | None
    risk_band:str | None
    risk_score:float | None
    max_amount:float | None
    pricing :float | None
    max_tenor :float | None
    net_to_gross :float | None
    inflow_median :float | None
    base_net :float | None
    cv_net :float | None
    persistence :float | None
    zeroing_rate :float | None
    disposable_income :float | None
    slope :float | None
    betting_count :int | None
    balance_floor :float | None
    salary:float | None
    customer_type:str | None
    existing_dtir :float | None
    installment :float | None
    principal_offer :float | None
    max_yield :float | None
    ineligibility_reasons:List[IneligibilityReason] | None = None

    class Config:
        from_attributes = True